[package]
name = "rusty-monkey"
version = "0.2.0"
authors = ["maxime <matrem@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
